# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Self-HostedPool'

variables:
  - group: KanbanApiVariables
  - name: azureSubscription
    value: 'c0b6260c-f90c-4c7a-9f1a-3ea57b1cebf2'
  - name: webAppName
    value: 'kanban-project'
  - name: environmentName
    value: 'kanban-project'


  # Azure Resource Manager connection created during pipeline creation
  #azureSubscription: 'c0b6260c-f90c-4c7a-9f1a-3ea57b1cebf2'
  
  # Web app name
  #webAppName: 'kanban-project'

  # Environment name
  #environmentName: 'kanban-project'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Self-HostedPool'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
    - script: |
        echo "$(DATABASE_CONNECTION_STRING)"
        echo "$(JWT_SECRET)"
        echo "$(PORT)"
        echo $(KanbanApiVariables)
      displayName: "Check Variables"


    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      name: 'Self-HostedPool'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: kanban-project'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|20LTS'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              appSettings: |
                MONGO_DB_CONNECTION=$(DATABASE_CONNECTION_STRING) 
                JWT_SECRET=$(JWT_SECRET)
              startUpCommand: 'npm run serve'